listen: ":8080"
allow_local_network: true

plugins:
  dir: "./examples/plugins"
  chain:
    - name: auth
    - name: add-header
    - name: rate-limit
      config:
        key_header: "X-Forwarded-For"
        capacity: 5
        refill_rate: 1

