listen: ":8080"
allow_local_network: true

plugins:
  dir: "./examples/plugins"
  chain:
    - name: auth
    - name: add-header
    - name: caching
      config:
        max_size: "100"
        default_ttl: "60"
